baseURL = "https://www.bkmi.ch/"
languageCode = "de-ch"
title = "Baukoma-Marketimpact"
theme = "airspace-hugo"


[menu]

  [[menu.header]]
    weight = 2
    name = "Work"
    url = "/work"
  [[menu.header]]
    weight = 3
    name = "News"
    url = "/blog"
  [[menu.header]]
    weight = 4
    name = "Dienstleistungen"
    url = "/service"
  [[menu.header]]
    weight = 5
    name = "Kontakt"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "Über uns"
    url = "#"
  [[menu.footer]]
    weight = 2
    name = "Kontakt"
    url = "#"
  [[menu.footer]]
    weight = 3
    name = "Events"
    url = "#"
  [[menu.footer]]
    weight = 4
    name = "News"
    url = "#"
  [[menu.footer]]
    weight = 5
    name = "Impressum"
    url = "#"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "b,m!"
    subtitle = "subtitle"
    logo = "/img/logo.png"

  [params.wrapper]
    enable = true
    title = "Über Baukoma-Marketimpact"
    italic = "Sie wollten schon immer gelben Kaffee, grüne Schokolade, rote Bananen oder blaue Zitronen ausprobieren? Bei uns sind Sie genau an der richtigen und kreativen Adresse."
    paragraph = "Die Baukoma-Marketimpact AG versteht sich als Marketingspezialistin für Unternehmen rund ums Bauen. Dazu gehören Handwerksbetriebe aller Art, Betriebe aus der Baustoffindustrie, Architekturbüros, Transport- und Materiallogistiker im Baubereich, Immobilienbüros, usw.     Dank jahrelanger Branchenkenntnissen, Einblicken in die Firmen und ihre Entscheidungswege auf Kader- und Inhaberebene ist die Baukoma-Marketimpact AG in der Lage, ihren Kunden einen umfassenden Mehrwert zu bieten. Schnelle, direkte und unkomplizierte, den Bedürfnissen und dem Tempo des Bauens angepasste Lösungen. Von der Beratung und Planung bis zur Durchführung; alles aus einer Hand rund ums Bauen und Wohnen!"

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "Unser Team"
    content = "Das Team der Baukoma AG mit seinem vielfältigen Angebot und der langjährigen Erfahrung, versteht sich als Generalunternehmer in der Welt des Marketings und der Kommunikation. Mit Spezialisten in allen Bereichen sind wir Ihr idealer Partner für eine langfristige und nachhaltige Zusammenarbeit. Auch bei aussergewöhnlichen Projekten können wir Sie dank unserem grossen Netzwerk an ausgewiesenen Partnern ideal begleiten. Wir haben uns zum Ziel gesetzt, Sie persönlich und professionell in der Umsetzung Ihrer Aufgaben zu unterstützen."
    [params.feature.button]
      caption = "View Works"
      url = "#"

  [params.call]
    enable = true
    title = "We design delightful digital experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

  [params.contact]
    enable = true
    title = "Konntaktieren Sie uns"
    subtitle = "Hinterlassen Sie uns eine unverbindliche Anfrage und wir melden uns schon bald bei Ihnen."
    [params.contact.form]
      name = "Ihr Name"
      email = "Ihre E-Mail"
      subject = "Ihr Anliegen"
      message = "Ihre Nachricht"
      button = "Absenden"
    [params.contact.box]
      title = "Baukoma-Marketimpact"
      address = "Rainackerstrasse 4 . Postfach 111 . 4562 Biberist . "
      email = "info@baukoma.ch"
      phone = "T +41 31 755 85 84 . F +41 31 755 85 82"
    [params.contact.gmaps]
      title = "Unser Standort"
