baseURL = "https://www.baukoma-marketimpact.ch/"
languageCode = "de-ch"
title = "Baukoma-Marketimpact"
#theme = "airspace-hugo"
theme = "hugo-elate-theme"


#[menu]
#
#  [[menu.header]]
#    weight = 2
#    name = "Work"
#    url = "/work"
#  [[menu.header]]
#    weight = 3
#    name = "News"
#    url = "/blog"
#  [[menu.header]]
#    weight = 4
#    name = "Dienstleistungen"
#    url = "/service"
#  [[menu.header]]
#    weight = 5
#    name = "Kontakt"
#    url = "/contact"
#
#  [[menu.footer]]
#    weight = 1
#    name = "Über uns"
#    url = "#"
#  [[menu.footer]]
#    weight = 2
#    name = "Kontakt"
#    url = "#"
#  [[menu.footer]]
#    weight = 3
#    name = "Events"
#    url = "#"
#  [[menu.footer]]
#    weight = 4
#    name = "News"
#    url = "#"
#  [[menu.footer]]
#    weight = 5
#    name = "Impressum"
#    url = "#"
#
## The site's parameters
#[params]
#
#  # If you want to remove the copyright text you need a Themefisher license.
#  # This license is offered with a 50% discount for all Hugo users.
#  # For information see https://github.com/gohugoio/hugoThemes/issues/260
#  
#  
#  #elate
#  custom_css = ["css/custom1.css"]
#  # Meta
#  author = ""
#  description = ""
#  email = ""
#
#
#  #airspace
#  dateFormat = "6 January 2006"
#
#  home = "Home"
#
#  [params.slider]
#    enable = true
#    title = "b,m!"
#    subtitle = "subtitle"
#    logo = "/img/logo.png"
#
#  [params.wrapper]
#    enable = true
#    title = "Über Baukoma-Marketimpact"
#    italic = "Sie wollten schon immer gelben Kaffee, grüne Schokolade, rote Bananen oder blaue Zitronen ausprobieren? Bei uns sind Sie genau an der richtigen und kreativen Adresse."
#    paragraph = "Die Baukoma-Marketimpact AG versteht sich als Marketingspezialistin für Unternehmen rund ums Bauen. Dazu gehören Handwerksbetriebe aller Art, Betriebe aus der Baustoffindustrie, Architekturbüros, Transport- und Materiallogistiker im Baubereich, Immobilienbüros, usw.     Dank jahrelanger Branchenkenntnissen, Einblicken in die Firmen und ihre Entscheidungswege auf Kader- und Inhaberebene ist die Baukoma-Marketimpact AG in der Lage, ihren Kunden einen umfassenden Mehrwert zu bieten. Schnelle, direkte und unkomplizierte, den Bedürfnissen und dem Tempo des Bauens angepasste Lösungen. Von der Beratung und Planung bis zur Durchführung; alles aus einer Hand rund ums Bauen und Wohnen!"
#
#  [params.blog]
#    enable = true
#    title = "Get The Latest On What We're doing"
#    subtitle = "Catch up with us, anytime and anywhere"
#
#  [params.feature]
#    enable = true
#    title = "Unser Team"
#    content = "Das Team der Baukoma AG mit seinem vielfältigen Angebot und der langjährigen Erfahrung, versteht sich als Generalunternehmer in der Welt des Marketings und der Kommunikation. Mit Spezialisten in allen Bereichen sind wir Ihr idealer Partner für eine langfristige und nachhaltige Zusammenarbeit. Auch bei aussergewöhnlichen Projekten können wir Sie dank unserem grossen Netzwerk an ausgewiesenen Partnern ideal begleiten. Wir haben uns zum Ziel gesetzt, Sie persönlich und professionell in der Umsetzung Ihrer Aufgaben zu unterstützen."
#    [params.feature.button]
#      caption = "View Works"
#      url = "#"
#
#  [params.call]
#    enable = true
#    title = "We design delightful digital experiences."
#    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

#  [params.contact]
#    enable = true
#    title = "Konntaktieren Sie uns"
#    subtitle = "Hinterlassen Sie uns eine unverbindliche Anfrage und wir melden uns schon bald bei Ihnen."
#    [params.contact.form]
#      name = "Ihr Name"
#      email = "Ihre E-Mail"
#      subject = "Ihr Anliegen"
#      message = "Ihre Nachricht"
#      button = "Absenden"
#    [params.contact.box]
#      title = "Baukoma-Marketimpact"
#      address = "Rainackerstrasse 4 . Postfach 111 . 4562 Biberist . "
#      email = "info@baukoma.ch"
#      phone = "T +41 31 755 85 84 . F +41 31 755 85 82"
#    [params.contact.gmaps]
#      title = "Unser Standort"
      
      
      
      
      
      
  #elate theme
  #custom css
  [params]
  custom_css = ["css/bkmi.css"]
  
  
  # Hero section
  [params.hero]
  title = '<div class="logo bkmi"><img src="img/bmAG_RGB.svg" ></div>'
   #subtitle = 'Another free HTML5 bootstrap template by <a href="http://freehtml5.co/" target="_blank" title="Free HTML5 Bootstrap Templates">FREEHTML5.co</a> released under <a href="http://creativecommons.org/licenses/by/3.0/" target="_blank">Creative Commons 3.0</a><br> ported for Hugo by <a href="http://saey55.gitlab.io/pietercv" target="_blank">Pieter Saey</a>'
  background = 'img/wall.jpg'
  
  [params.hero.stripe]
  enable = true
  
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Plan"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Get In Touch"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Develop"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Click Me"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Launch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Why us?"
    icon = "icon-rocket"
    img = "img_10.jpg"
    
    
  [[params.intro.item]]
    title = "Develop"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Click Me"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Launch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Why us?"
    icon = "icon-rocket"
    img = "img_10.jpg"


  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"



  # Work section
  [params.work]
    enable = true
    title = "Work"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"



  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"
    



  # Services section
  [params.services]
    enable = true
    title = "Unsere Dienstleistungen"
    description = "Bei uns stehen Kreativität, Fachwissen und Effizienz an erster Stelle. Zusammen sind wir ein Team und verfolgen ein Ziel, nämlich erfolgreich zu sein. Wir arbeiten als Fullservice-Agentur oder begleiten Sie modular in den von Ihnen gewünschten Bereichen."

    [[params.services.item]]
      title = "Consulting"
      description = "Seit vielen Jahren beraten und begleiten wir Unternehmen in verschiedenen Funktionen. Unser Spezialgebiet ist alles 'rund ums Bauen', aber wir beraten auch Unternehmen aus allen anderen Bereichen kompetent."
      icon = "icon-stethoscope"
      
    [[params.services.item]]
      title = "Strategie und Branding"
      description = "Modernes Kommunikationsdesign beinhaltet verschiedene Bereiche, wie beispielsweise das traditionelle Grafikdesign, Web-Konzepte bis hin zu den sozialen Medien."
      icon = "icon-compass"
      
      
      [[params.services.item]]
      title = "Marketing"
      description = "Ein wirkungsvolles Marketing und die zielgruppenorientierte Kommunikation können nicht standardisiert werden. Wir analysieren zusammen Ihre individuelle Situation, strukturieren und erarbeiten die Ziele und setzen diese mit Ihnen um."      
      icon = "icon-heart"
      
          [[params.services.item]]
      title = "Produktion"
      description = "Wir arbeiten vorwiegend als Fullservice-Agentur. Somit haben Sie mit uns einen Ansprechpartner auf den Sie sich gänzlich verlassen können. Wir arbeiten mit auserwählten Partnern zusammen, koordinieren Termine und garantieren so höchste Qualitätsansprüche."      
      icon = "icon-diamond"
      
    [[params.services.item]]
      title = "Fotografie"
      description = "«Die andere Art gesehen zu werden» Unter diesem Motto halten wir Ihre wichtigsten Momente fest. Ihre Mitarbeitenden, Geschäfts- und Produktionsräume, Bauwerke und Events werden bildlich in einem guten Licht dastehen. Die Aufnahmen machen wir entweder bei uns im Fotostudio oder am Ort des Geschehens. Professionelle und eindrucksvolle Bilder, die für sich und für Sie sprechen."
      icon = "icon-camera"
      

      
    [[params.services.item]]
      title = "Events"
      description = "Firmenjubiläen, Tage der offenen Türen, Generalversammlungen oder andere Veranstaltungen. Wir begleiten Sie nach Ihren individuellen Wünschen und unter Berücksichtigung der Budgets."      
      icon = "icon-rocket"    
      


[[params.services.item]]
      title = "Grafik"
      description = "In unserem Atelier stellen wir sicher, dass Ihr Auftritt harmonisch, umfassend und als Einheit konzipiert und umgesetzt wird."      
      icon = "icon-magic"
      
      
[[params.services.item]]
      title = "Web.etc"
      description = "Die Zufrindenheit unserer Kundinnen und unserer Kunden steht steets im mittelpunkt bei unserem tun. Egal ob Website oder Mobile-App, Social-Media Kampagne oder online Game, wir begleiten Sie effizient und mit begeisterung auf ihrem Weg durch die Digitalen möglichkeiten."      
      icon = "icon-hand-pointer-o"



  # About section
  [params.about]
    enable = true
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Jean Smith"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]      

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "img/wall.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000



  # Contact section

  
  [params.contact]
    enable = true
    google_iframe_map = true
    google_iframe_embedcode = '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2711.5214626277566!2d7.554953615855999!3d47.186805179159045!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x478e140c6995ba39%3A0x82b1e8190e45d8!2sBaukoma+AG!5e0!3m2!1sde!2sch!4v1533532499415" width="100%" height="400" frameborder="0" style="border:0" allowfullscreen></iframe>'
    google_api_map = false
    form = true
    title = "Konntaktieren Sie uns"

    description = "Hinterlassen Sie uns eine unverbindliche Anfrage und wir melden uns schon bald bei Ihnen."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Baukoma-Marketimpact . 5ainackerstrasse 4 . Postfach 111 . 4562 Biberist"],
        ["icon-phone", "T +41 31 755 85 84 . F +41 31 755 85 82"],
        ["icon-envelope", "info@baukoma-marketimpact.ch"],
        ["icon-globe", '<a href="//www.baukoma-marketimpact.ch" target="_blank">www.baukoma-marketimpact.ch</a>']
      ]

    name = "Ihr Name"
    email = "Ihre E-Mail"
    phone = "Telefon"
    subject = "Ihr Anliegen"
    message = "Ihre Nachricht"
    button = "Absenden"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]
