baseURL = "https://www.baukoma-marketimpact.ch/"
languageCode = "de-ch"
title = "Baukoma-Marketimpact"
theme = "hugo-elate-theme"



  #-----------------------------------------------------------------------------------------------------#
  #Menu Header
  [menu]
  
  [[menu.header]]
  weight = 3
  name = "Blog"
  url = "/blog"
  
  #-----------------------------------------------------------------------------------------------------#
  #elate theme
  #custom css
  [params]
  dateFormat = "6 January 2006"
  home = "Home"
  custom_css = ["css/bkmi.css"]
  
  #-----------------------------------------------------------------------------------------------------#
  # Hero section
  [params.hero]
  # title = '<div class="bkmi"><img src="img/Logo_bmAG_RGB.png" ></div>'
  subtitle = ""
  image = 'img/Logo_bmAG_RGB.png'
  background = 'img/backgroundbulp.jpg'
  
  [params.hero.stripe]
  enable = true
  
  #-----------------------------------------------------------------------------------------------------#
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]
  title = "Unsere Arbeiten"
  description = ""

  [params.intro.new_layout]
  enable = true
  
  [params.intro.old_layout]
  enable = false
  
  [params.intro.video]
  enable = false
  title = "Watch the video"
  icon = "icon-play2"
  url = "https://vimeo.com/channels/staffpicks/93951774"
  
  #-----------------------------------------------------------------------------------------------------#
  # Services section
  [params.services]
  enable = true
  title = "Unsere Dienstleistungen"
  description = "Bei uns stehen Kreativität, Fachwissen und Effizienz an erster Stelle. Zusammen sind wir ein Team und verfolgen ein Ziel, nämlich erfolgreich zu sein. Wir arbeiten als Fullservice-Agentur oder begleiten Sie modular in den von Ihnen gewünschten Bereichen."
  
  [[params.services.item]]
  title = "Events"
  description = "Firmenjubiläen, Tage der offenen Türen, Generalversammlungen oder andere Veranstaltungen. Wir begleiten Sie nach Ihren individuellen Wünschen und unter Berücksichtigung des Budgets."      
  icon = "icon-rocket"    
  
  [[params.services.item]]
  title = "Consulting"
  description = "Seit vielen Jahren beraten und begleiten wir Unternehmen in verschiedenen Funktionen. Unser Spezialgebiet ist alles «rund ums Bauen», aber wir beraten auch Unternehmen aus allen anderen Bereichen kompetent."
  icon = "icon-stethoscope"
  
  [[params.services.item]]
  title = "Marketingberatung"
  description = "Jedes Unternehmen befindet sich irgendwo auf der Erfolgsleiter. Wer noch weit unten ist, möchte Massnahmen ergreifen um auf die nächste Stufe aufzusteigen, wer weit oben ist, will darum kämpfen um auf diesem Level zu bleiben. Wir analysieren und entwickeln zusammen mit unseren Kunden die richtigen Strategien dafür."      
  icon = "icon-road"

  [[params.services.item]]
  title = "Workwear"
  description = "Was in einer Sportmannschaft das Trikot ist, ist in der Arbeitswelt das T-Shirt, das Business-Hemd oder die Arbeitsjacke. Tragen Sie Ihre Firma nach aussen, treten Sie sichtbar als Team auf! Wir besticken und bedrucken die Textilien und lassen Sie darin noch besser aussehen."      
  icon = "icon-user-md"
  

  # [[params.services.item]]
  # title = "Strategie und Branding"
  # description = "Modernes Kommunikationsdesign beinhaltet verschiedene Bereiche, wie beispielsweise das traditionelle Grafikdesign, Web-Konzepte bis hin zu den sozialen Medien."
  # icon = "icon-compass"
  
  
  # [[params.services.item]]
  # title = "Marketing"
  # description = "Ein wirkungsvolles Marketing und die zielgruppenorientierte Kommunikation können nicht standardisiert werden. Wir analysieren zusammen Ihre individuelle Situation, strukturieren und erarbeiten die Ziele und setzen diese mit Ihnen um."      
  # icon = "icon-heart"
  
  [[params.services.item]]
  title = "Produktion / Werbeartikel"
  description = "Ob Drucksachen, Buchproduktionen, Werbetechnik, Werbeartikel oder vielem mehr: wir arbeiten als Fullservice-Agentur mit auserwählten Partnern zusammen, gestalten, koordinieren Termine und garantieren so höchste Qualität."      
  icon = "icon-diamond"
  
  [[params.services.item]]
  title = "Web"
  description = "Die Zufriedenheit unserer Kundinnen und unserer Kunden steht stets im Mittelpunkt bei unserem Tun. Egal ob Website oder Mobile-App, Social-Media Kampagne oder Online-Game, wir begleiten Sie effizient und mit Begeisterung auf ihrem Weg durch die digitalen Möglichkeiten."      
  icon = "icon-hand-pointer-o"
  
  [[params.services.item]]
  title = "Fotografie"
  description = "«Die andere Art gesehen zu werden» Unter diesem Motto halten wir Ihre wichtigsten Momente fest. Die Aufnahmen machen wir entweder bei uns im Fotostudio oder am Ort des Geschehens. Professionelle und eindrucksvolle Bilder, die für sich und für Sie sprechen."
  icon = "icon-camera"
  
  [[params.services.item]]
  title = "Grafik"
  description = "In unserem Atelier stellen wir sicher, dass Ihr Auftritt harmonisch, umfassend und als Einheit konzipiert und umgesetzt wird."      
  icon = "icon-magic"


  #-----------------------------------------------------------------------------------------------------#
  # About section
  [params.about]
  enable = true
  title = "Unser Team"
  description = "Die Baukoma-Marketimpact AG versteht sich als Generalunternehmer in der Welt des Marketings und der Kommunikation. Mit Spezialisten in allen Bereichen sind wir Ihr idealer Partner für eine langfristige und nachhaltige Zusammenarbeit. Auch bei aussergewöhnlichen Projekten können wir Sie dank unserem grossen Netzwerk an ausgewiesenen Partnern ideal begleiten. Wir haben uns zum Ziel gesetzt, Sie persönlich und professionell in der Umsetzung Ihrer Aufgaben zu unterstützen."
  
  [[params.about.item]]
  name = "Urs Bratschi Reichelt"
  position = "Geschäftsführer"
  description = "Urs Bratschi Reichelt ist Gründer, Geschäftsführer und Inhaber der Baukoma-Marketimpact AG. Er hat über 20 Jahre Führungserfahrung in der Baubranche."
  img = "img/team/u-b.png"
  alt = "Urs Bratschi Reichelt – Geschäftsführer"
  social = [
    ["icon-mail2", "mailto:u-b@baukoma-marketimpact.ch"]
  ]
  
  [[params.about.item]]
  name = "Oliver Bratschi"
  position = "Administration / Marketingassistenz"
  description = "Oliver Bratschi ist ausgebildeter Kaufmann mit Berufsmatura. Er betreut administrative Aufgaben und unterstützt diverse Marketingprojekte."
  img = "img/team/o-b.png"
  alt = "Oliver Bratschi – Administration / Marketingassistenz"
  social = [
    ["icon-mail2", "mailto:o-b@baukoma-marketimpact.ch"]
  ]
  
  [[params.about.item]]
  name = "Lenka Reichelt Bratschi"
  position = "Fotografin"
  description = "Lenka Reichelt Bratschi ist Fotografin. Sie stellt u.a. Architektur ins beste Licht, hält Events fest und ist verantwortlich für Firmen-, Team-, Portrait- und Modeaufnahmen."
  img = "img/team/l-r.png"
  alt = "Lenka Reichelt Bratschi – Fotografin"
  social = [
    ["icon-mail2", "mailto:foto@baukoma-marketimpact.ch"]
  ]
  
  [[params.about.item]]
  name = "Sandra Kummer"
  position = "Grafik"
  description = "Sandra Kummer ist Polygrafin und zuständig für die visuelle Gestaltung inkl. Druckvorstufe. Kreativität und Grafik ist ihr Metier."
  img = "img/team/s-k.png"
  alt = "Sandra Kummer – Grafik"
  social = [
    ["icon-mail2", "mailto:s-k@baukoma-marketimpact.ch"]
  ]
  
  [[params.about.item]]
  name = "Tobias Haffner"
  position = "Web- und Social-Media-Artist"
  description = "Tobias Haffner ist ausgebildeter Informatiker mit Berufsmatura. Er ist zuständig für die Konzeption und Umsetzung von Webseiten und Online-Kampagnen."
  img = "img/team/t-h.png"
  alt = "Tobias Haffner – Web- und Social-Media-Artist"
  social = [
    ["icon-mail2", "mailto:t-h@baukoma-marketimpact.ch"]
  ]
  
  #-----------------------------------------------------------------------------------------------------#
  # Work section
  [params.work]
  enable = false
  title = "News"
  description = ""
  footertext = ""
  
  [[params.work.row]]
  img = "img/16_slider_news_dienst.jpg"
  alt = "Wir Feiern Uns!"
  title = "1. Sep 2018"
  subtitle = "Wir sind eins!"
  
  [[params.work.row]]
  img = "img/b2berne-jetztanmelden.png"
  alt = "Image2"
  title = "1. Sep 2018"
  subtitle = "Die mobile Fussgängerbrücke zum Jet d'Eau gewinnt Building-Award 2017"
  
  
    
  #-----------------------------------------------------------------------------------------------------#
  # Contact section
  [params.organizer]
  enable = false
  title = "Wir sind Veranstallter von"
  description = ""
  
    [[params.organizer.event]]
    link = "//www.marketingarchitektur.ch"
    img-url = "img/events/AfMA.png"
    
    [[params.organizer.event2]]
    link = "//www.b2berne.ch"
    img-url = "Logo_b2berne_KMU_cmyk.png"
  
  #-----------------------------------------------------------------------------------------------------#
  # Contact section
  [params.contact]
  enable = true
  google_iframe_map = true
  google_iframe_embedcode = '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d43384.34006453065!2d7.539632807656666!3d47.186809262625395!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x478e140c6995ba39%3A0x82b1e8190e45d8!2sBaukoma+AG!5e0!3m2!1sde!2sch!4v1535377108097" width="100%" height="500" frameborder="0" style="border:0" allowfullscreen></iframe>'
  google_api_map = false
  form = false
  title = "Kontaktieren Sie uns"
  description = "Wir haben immer ein offenes Ohr und gute Ideen. Wir freuen uns auf Ihren Anruf, eine Nachricht und noch mehr über Ihren Besuch."
  # Available icons: http://simplelineicons.com/
  details = [
    ["icon-home", "Baukoma-Marketimpact AG . Rainackerstrasse 4 . Postfach CH-4562 Biberist"],
    ["icon-phone", "T +41 31 755 85 84"],
    ["icon-envelope", "info@baukoma-marketimpact.ch"],
    ["icon-globe", '<a href="//www.baukoma-marketimpact.ch" target="_blank">www.baukoma-marketimpact.ch</a>']
  ]
  
  name = "Ihr Name"
  email = "Ihre E-Mail"
  phone = "Telefon"
  subject = "Ihr Anliegen"
  message = "Ihre Nachricht"
  button = "Absenden"
  


  
  
  [params.blog]
  enable = true
  title = "Get The Latest On What We're doing"
  subtitle = "Catch up with us, anytime and anywhere"


  
  
  
  #-----------------------------------------------------------------------------------------------------#
  
  
    # Testimonials section
  [params.testimonials]
  enable = false
  title = "Testimonials"
  description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
  
  [[params.testimonials.item]]
  quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
  person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
  img = "person1.jpg"
  alt = "Person1"
  
  [[params.testimonials.item]]
  quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
  person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
  img = "person2.jpg"
  alt = "Person2"
  
  [[params.testimonials.item]]
  quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
  person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
  img = "person3.jpg"
  alt = "Person3"
  
  
  # Counters section
  [params.counters]
  enable = false
  title = "Zahlen"
  background = "img/wall.jpg"
  
  [[params.counters.item]]
  description = "Events durchgeführt"
  icon = "icon-bullhorn"
  from = 0
  to = 48
  interval = 50
  speed = 5000
  
  [[params.counters.item]]
  description = "Fotoshootings"
  icon = "icon-camera"
  from = 0
  to = 302
  interval = 50
  speed = 5000
  
  [[params.counters.item]]
  description = "Umgesetzte Layouts "
  icon = "icon-paint-brush"
  from = 0
  to = 630
  interval = 50
  speed = 5000
  
  [[params.counters.item]]
  description = "Zufridene Kunden"
  icon = "icon-people"
  from = 0
  to = 248
  interval = 50
  speed = 5000


  # Footer section
  [params.footer]
  enable = false
  copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
  links = [
    ["icon-twitter", "#twitter"],
    ["icon-facebook", "#facebook"],
    ["icon-youtube", "#youtube"]
  ]